services:
  # PostgreSQL
  postgres:
    container_name: "postgres"
    image: arm64v8/postgres
    environment:
      POSTGRES_USER: "username"
      POSTGRES_PASSWORD: "password"
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - database_network
    restart: unless-stopped
  
  # pgAdmin
  pgadmin:
    container_name: "pgadmin"
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@mail.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "8081:80"
    networks:
      - database_network
    restart: unless-stopped

  # MySQL
  mysql:
    container_name: "mysql"
    image: arm64v8/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "mydb"
    volumes:
       - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - database_network
    restart: unless-stopped

  # phpMyAdmin
  phpmyadmin:
    container_name: "phpmyadmin"
    image: arm64v8/phpmyadmin
    environment:
      PMA_HOST: "mysql"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "8080:80"
    networks:
      - database_network
    restart: unless-stopped

  # MongoDB
  mongodb:
    container_name: "mongodb"
    image: arm64v8/mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: "username"
      MONGO_INITDB_ROOT_PASSWORD: "password"
    volumes:
       - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - database_network
    restart: unless-stopped

networks:
  database_network:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mysql_data:
  mongodb_data:
